services:
  _defaults:
    autowire: true
    autoconfigure: true

  Ivo\AutoMetaBundle\:
    resource: "../../../AutoMetaBundle/"
    exclude:
      - "../../DependencyInjection/"
      - "../../Resources/contao/"
